### PR TITLE
Add tests for DockerfileInstallParser

### PR DESCRIPTION
**Pull request by OlawumiSalaam**
Thank you for taking your time to contribute to Ersilia, just a few checks before we proceed

- [x]  Have you followed the guidelines in our [Contribution Guide](https://github.com/ersilia-os/ersilia/blob/master/CONTRIBUTING.md)
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

**Description**
This task is to test parser module with as many edge cases as possible. For `parser.py `module we want to test `Add tests for DockerfileInstallParser` class. the existing parser module provides classes to parse installation instructions from YAML files and Dockerfiles, generate bash scripts from these instructions, and convert metadata from YAML format to JSON. The parser.py has the following classes:

- `InstallParser`: An abstract base class for handling installation files. It defines the core functionality for getting the Python executable path, checking for conda commands and converting commands to a bash script. It also writes the generated bash script to a file.
- `YAMLInstallParser`: Inherits from InstallParser and is designed to parse a` install.yml `file for Python version and installation commands. It expects the YAML file to have a structure that includes Python version and installation commands.
- `DockerfileInstallParser`: Inherits from InstallParser and parses a Dockerfile for Python version and installation commands. It extracts `RUN pip` or `RUN conda` commands and converts them into a list format.
- `MetadataYml2JsonConverter`: Converts metadata from YAML to JSON. It allows flexible handling of YAML keys and ensures they are converted to JSON in a consistent format.

This task adds unit tests for the `DockerfileInstallParser` class within the Ersilia-pack. The ensures that the class can accurately parse Dockerfiles for `pip` and` conda` installation commands and handle various command structures. 

**Changes to be made**

- To refactor the provided code into a sub-package structure instead of having each class in a single file using these steps:

1. Create a directory and organize the classes into a sub-package directory.
2. Create `__init__.py`. The` __init__.py` file allows us to import the classes as part of a single package and makes it easier to work with.
3. Separate classes by moving each class into its own module file.
This helps us maintain clean and organized code.

- Create a test file named test_dockerfile_install_parser.py in the same directory as DockerfileInstallParser in ersilia-pack.

1. Added test `test_get_python_version` to confirm that the `get_python_version` method correctly identifies the Python version specified in the Dockerfile. 
2. Added test `test_process_pip_command` to tests the _`process_pip_command` method, ensuring that it properly parses a standard `pip install` command with a specified package version.
3. Added` test_process_conda_command`. It tests the `_process_conda_command` method to confirm it accurately parses a `conda install` command with a specified package version and default channel.

**Testing**

When I tried to run the test locally, I got `ValueError: Python version not found in Dockerfile`, occured in the _get_python_version method. This means that the method is unable to extract the Python version from the Dockerfile as expected. While debugging, I realised that the Dockerfile specifies `FROM python:3.10-slim` and in the `_get_python_version`  function ,the regular expression `m=re.search(r"py(\d+) + 1)" `is trying to match a string in the format `py<version>` which does not exist in the Dockerfile. The correct format in the Dockerfile is `python:<version>.`
To resolve the issue, I updated the `_get_python_version()` method to return the full version tag (3.10-slim) using this line of code `m = re.search(r"python:(\d+\.\d+(-\w+)?)", l)`
After updating the change, the all the test case passed returning output `Ran 3 tests in 0.002s
OK`

Status

1. Added tests for `_get_python_version` to confirm that the correct Python version is parsed from the `FROM` command in the Dockerfile.
2. Added testing for` _process_pip_command` and `_process_conda_command`
3. Pushed changes to the feature-dockerfile-Install-parser-test branch for review.

**To do**

- Add additional tests to cover other scenarios

Is this pull request related to any open issue? If yes, replace issueID below with the issue ID
Yes,
Related to [#26](https://github.com/ersilia-os/ersilia-pack/issues/26)

### CODE REVIEW

**Comment by OlawumiSalaam** [comment]
@DhanshreeA I have added tests for DockerfileInstallParser class. Please review and give feedback. Happy to learn from you. Thank you

**Comment by P-Mefut** [comment]
hi @OlawumiSalaam is there any reason for breaking the `parser.py` file into sub class files?... because i think it just makes the repo  have redundant data files...

**Comment by OlawumiSalaam** [comment]
@P-Mefut. Thank you for your feedback. If you open the parser.py, the instruction is stated there. And here are the reason:
each class can handle a specific aspect of the parsing logic and make it easier to understand. In terms of scalability, it  allows for easier addition of new features without cluttering a single file. @DhanshreeA mentioned that this is an evolving issue
And particularly, focused classes are be easier to test in isolation, leads to more effective unit tests and a higher level of code coverage. I think it is a good practice when working in collaborative environment as ersilia where multiple contributors are working on different aspects of the parser simultaneously without causing merge conflicts. The mentor created 3 task for the classes in `parser.py` and assigned to different contributors.
In as much as we do not want redundancy in the codebase, there should be a trade-off maintainability, readability, and scalability.
If after the mentors sees it as unnecessary, I will consolidate based on the feedback. This is a journey of continuous learning.

**Comment by P-Mefut** [comment]
Thanks @OlawumiSalaam I didn't quite go through the parser file to see the to do instructions... good catch and reminder for me

**Comment by OlawumiSalaam** [comment]
@P-Mefut Thank you for your feedback as always.

**Comment by OlawumiSalaam** [comment]
@DhanshreeA please kindly review. Thank you.

**Comment by DhanshreeA** [comment]
@OlawumiSalaam fantastic work as always! Please see my comment [here](https://github.com/ersilia-os/ersilia-pack/issues/26#issuecomment-2419371269). Could you create a `fixtures` sub-directory within `tests` and store the reference files I have mentioned in the linked comment there. This would help with actually setting up test cases.

**Comment by DhanshreeA** [comment]
Thank you both @OlawumiSalaam and @P-Mefut for the lively discussion! Much appreciated!

**Comment by OlawumiSalaam** [comment]
### **Review of the Test Implementation**
I added tests for `DockerfileInstallParser` and implemented @DhanshreeA's feedback in the steps highlighted below:

- [x] I created the fixtures directory within the tests folder. I stored the reference file mentioned in the [linked comment](https://github.com/ersilia-os/ersilia-pack/issues/26#issuecomment-2419371269) inside the [fixtures directory](https://github.com/OlawumiSalaam/ersilia-pack/tree/feature-dockerfile-Install-parser-test/tests/fixtures). The reference files are [install.yml](https://github.com/ersilia-os/eos3ujl/blob/main/install.yml) and [Dockerfile](https://github.com/ersilia-os/eos5gge/blob/main/Dockerfile).

- [x]  I used `pytest` syntax (fixtures and parameterized tests) in the test implementation as shown below:

- I used `@pytest.fixture` , I defined a function as `dockerfile_path` to provide the relative path to the `Dockerfile.txt` located in the `fixtures` directory. 
- I tested the function of _get_python_version method in the DockerfileInstallParser class to confirm that the correct Python version is parsed from the Dockerfile. The test method is defined as `test_get_python_version` and path to the Dockerfile (`dockerfile_path`) is set as parameter.
- I added test to check the function  `_process_pip_command`. The test defined as `test_process_pip_command` assert that the output  match the expected command. 
- I added test to check `_process_conda_command` method. The test defined as `test_process_conda_command` asserts that the parsed output from the DockerfileInstallParser matches the expected command.

### **Testing locally**
I used the `pytest tests/test_dockerfile_install_parser.py > test_dockerfile_install_parser_output.txt` to run the test and all tests passed. This is logged output file.
[test_dockerfile_install_parser_output.txt](https://github.com/user-attachments/files/17447403/test_dockerfile_install_parser_output.txt)

**Comment by OlawumiSalaam** [comment]
@DhanshreeA  please kindly review and give feedback. Thank you.

**Comment by OlawumiSalaam** [comment]
> ### **Review of the Test Implementation**
> I added tests for `DockerfileInstallParser` and implemented @DhanshreeA's feedback in the steps highlighted below:
> 
> * [x]  I created the fixtures directory within the tests folder. I stored the reference file mentioned in the [linked comment](https://github.com/ersilia-os/ersilia-pack/issues/26#issuecomment-2419371269) inside the [fixtures directory](https://github.com/OlawumiSalaam/ersilia-pack/tree/feature-dockerfile-Install-parser-test/tests/fixtures). The reference files are [install.yml](https://github.com/ersilia-os/eos3ujl/blob/main/install.yml) and [Dockerfile](https://github.com/ersilia-os/eos5gge/blob/main/Dockerfile).
> * [x]   I used `pytest` syntax (fixtures and parameterized tests) in the test implementation as shown below:
> * I used `@pytest.fixture` , I defined a function as `dockerfile_path` to provide the relative path to the `Dockerfile.txt` located in the `fixtures` directory.
> * I tested the function of _get_python_version method in the DockerfileInstallParser class to confirm that the correct Python version is parsed from the Dockerfile. The test method is defined as `test_get_python_version` and path to the Dockerfile (`dockerfile_path`) is set as parameter.
> * I added test to check the function  `_process_pip_command`. The test defined as `test_process_pip_command` assert that the output  match the expected command.
> * I added test to check `_process_conda_command` method. The test defined as `test_process_conda_command` asserts that the parsed output from the DockerfileInstallParser matches the expected command.
> 
> ### **Testing locally**
> I used the `pytest tests/test_dockerfile_install_parser.py > test_dockerfile_install_parser_output.txt` to run the test and all tests passed. This is logged output file. [test_dockerfile_install_parser_output.txt](https://github.com/user-attachments/files/17447403/test_dockerfile_install_parser_output.txt)

**Comment by OlawumiSalaam** [comment]
@DhanshreeA Please kindly review my task. Thank you.

**Comment by DhanshreeA** [comment]
I think my biggest question here is @OlawumiSalaam why have you created two separate modules - parser and parsers which basically look identical to each other?

**Pull request closed without merging**
